// Country list for phone selector.
// Flag images expected in /public/Flags/<ISO2>.png (uppercase ISO 3166-1 alpha-2).
// Keep list reasonably sized (common countries + project target regions). Extend cautiously.
export const phoneCountries = [
  // Africa & MENA
  { code: 'DZ', name: 'Algérie', dialCode: '213' },
  { code: 'AO', name: 'Angola', dialCode: '244' },
  { code: 'BJ', name: 'Bénin', dialCode: '229' },
  { code: 'BW', name: 'Botswana', dialCode: '267' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '226' },
  { code: 'BI', name: 'Burundi', dialCode: '257' },
  { code: 'CM', name: 'Cameroun', dialCode: '237' },
  { code: 'CV', name: 'Cap-Vert', dialCode: '238' },
  { code: 'TD', name: 'Tchad', dialCode: '235' },
  { code: 'KM', name: 'Comores', dialCode: '269' },
  { code: 'CG', name: 'Congo', dialCode: '242' },
  { code: 'CI', name: 'Côte d’Ivoire', dialCode: '225' },
  { code: 'EG', name: 'Égypte', dialCode: '20' },
  { code: 'ER', name: 'Érythrée', dialCode: '291' },
  { code: 'ET', name: 'Éthiopie', dialCode: '251' },
  { code: 'GA', name: 'Gabon', dialCode: '241' },
  { code: 'GM', name: 'Gambie', dialCode: '220' },
  { code: 'GH', name: 'Ghana', dialCode: '233' },
  { code: 'GN', name: 'Guinée', dialCode: '224' },
  { code: 'KE', name: 'Kenya', dialCode: '254' },
  { code: 'LY', name: 'Libye', dialCode: '218' },
  { code: 'MG', name: 'Madagascar', dialCode: '261' },
  { code: 'MW', name: 'Malawi', dialCode: '265' },
  { code: 'ML', name: 'Mali', dialCode: '223' },
  { code: 'MA', name: 'Maroc', dialCode: '212' },
  { code: 'MU', name: 'Maurice', dialCode: '230' },
  { code: 'MR', name: 'Mauritanie', dialCode: '222' },
  { code: 'MZ', name: 'Mozambique', dialCode: '258' },
  { code: 'NA', name: 'Namibie', dialCode: '264' },
  { code: 'NE', name: 'Niger', dialCode: '227' },
  { code: 'NG', name: 'Nigéria', dialCode: '234' },
  { code: 'RW', name: 'Rwanda', dialCode: '250' },
  { code: 'SN', name: 'Sénégal', dialCode: '221' },
  { code: 'SC', name: 'Seychelles', dialCode: '248' },
  { code: 'ZA', name: 'Afrique du Sud', dialCode: '27' },
  { code: 'TZ', name: 'Tanzanie', dialCode: '255' },
  { code: 'TG', name: 'Togo', dialCode: '228' },
  { code: 'TN', name: 'Tunisie', dialCode: '216' },
  { code: 'UG', name: 'Ouganda', dialCode: '256' },
  { code: 'ZM', name: 'Zambie', dialCode: '260' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '263' },
  // Europe
  { code: 'DE', name: 'Allemagne', dialCode: '49' },
  { code: 'AT', name: 'Autriche', dialCode: '43' },
  { code: 'BE', name: 'Belgique', dialCode: '32' },
  { code: 'BG', name: 'Bulgarie', dialCode: '359' },
  { code: 'HR', name: 'Croatie', dialCode: '385' },
  { code: 'DK', name: 'Danemark', dialCode: '45' },
  { code: 'ES', name: 'Espagne', dialCode: '34' },
  { code: 'EE', name: 'Estonie', dialCode: '372' },
  { code: 'FI', name: 'Finlande', dialCode: '358' },
  { code: 'FR', name: 'France', dialCode: '33' },
  { code: 'GR', name: 'Grèce', dialCode: '30' },
  { code: 'HU', name: 'Hongrie', dialCode: '36' },
  { code: 'IE', name: 'Irlande', dialCode: '353' },
  { code: 'IT', name: 'Italie', dialCode: '39' },
  { code: 'LV', name: 'Lettonie', dialCode: '371' },
  { code: 'LT', name: 'Lituanie', dialCode: '370' },
  { code: 'LU', name: 'Luxembourg', dialCode: '352' },
  { code: 'MT', name: 'Malte', dialCode: '356' },
  { code: 'NL', name: 'Pays-Bas', dialCode: '31' },
  { code: 'NO', name: 'Norvège', dialCode: '47' },
  { code: 'PL', name: 'Pologne', dialCode: '48' },
  { code: 'PT', name: 'Portugal', dialCode: '351' },
  { code: 'RO', name: 'Roumanie', dialCode: '40' },
  { code: 'GB', name: 'Royaume-Uni', dialCode: '44' },
  { code: 'CZ', name: 'Tchéquie', dialCode: '420' },
  { code: 'SK', name: 'Slovaquie', dialCode: '421' },
  { code: 'SI', name: 'Slovénie', dialCode: '386' },
  { code: 'SE', name: 'Suède', dialCode: '46' },
  { code: 'CH', name: 'Suisse', dialCode: '41' },
  { code: 'UA', name: 'Ukraine', dialCode: '380' },
  { code: 'RU', name: 'Russie', dialCode: '7' },
  // Americas
  { code: 'AR', name: 'Argentine', dialCode: '54' },
  { code: 'BO', name: 'Bolivie', dialCode: '591' },
  { code: 'BR', name: 'Brésil', dialCode: '55' },
  { code: 'CA', name: 'Canada', dialCode: '1' },
  { code: 'CL', name: 'Chili', dialCode: '56' },
  { code: 'CO', name: 'Colombie', dialCode: '57' },
  { code: 'EC', name: 'Équateur', dialCode: '593' },
  { code: 'MX', name: 'Mexique', dialCode: '52' },
  { code: 'PE', name: 'Pérou', dialCode: '51' },
  { code: 'PY', name: 'Paraguay', dialCode: '595' },
  { code: 'UY', name: 'Uruguay', dialCode: '598' },
  { code: 'VE', name: 'Venezuela', dialCode: '58' },
  { code: 'US', name: 'États-Unis', dialCode: '1' },
  // Asia / Pacific
  { code: 'AU', name: 'Australie', dialCode: '61' },
  { code: 'BD', name: 'Bangladesh', dialCode: '880' },
  { code: 'CN', name: 'Chine', dialCode: '86' },
  { code: 'HK', name: 'Hong Kong', dialCode: '852' },
  { code: 'IN', name: 'Inde', dialCode: '91' },
  { code: 'ID', name: 'Indonésie', dialCode: '62' },
  { code: 'JP', name: 'Japon', dialCode: '81' },
  { code: 'MY', name: 'Malaisie', dialCode: '60' },
  { code: 'NZ', name: 'Nouvelle-Zélande', dialCode: '64' },
  { code: 'PK', name: 'Pakistan', dialCode: '92' },
  { code: 'PH', name: 'Philippines', dialCode: '63' },
  { code: 'SG', name: 'Singapour', dialCode: '65' },
  { code: 'KR', name: 'Corée du Sud', dialCode: '82' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '94' },
  { code: 'TH', name: 'Thaïlande', dialCode: '66' },
  { code: 'TR', name: 'Turquie', dialCode: '90' },
  { code: 'AE', name: 'Émirats Arabes Unis', dialCode: '971' },
  { code: 'VN', name: 'Vietnam', dialCode: '84' },
  { code: 'QA', name: 'Qatar', dialCode: '974' },
  { code: 'KW', name: 'Koweït', dialCode: '965' },
  { code: 'OM', name: 'Oman', dialCode: '968' },
  { code: 'BH', name: 'Bahreïn', dialCode: '973' },
  { code: 'JO', name: 'Jordanie', dialCode: '962' },
  { code: 'LB', name: 'Liban', dialCode: '961' },
];

export const findCountry = (code) => phoneCountries.find(c => c.code === code);